### ISSUE TITLE
Random loud noise, caused by playing song with wrong output audio format

### ISSUE THREAD

**Issue by nyanpasu64** [MusicPlayerDaemon/MPD#1900]
### Describe the bug
Randomly, when playing a short song (under 30 seconds or so), mpd instead outputs a loud garbled noise, accompanied by an incorrect longer song length shown on client apps.

## Expected Behavior
mpd does not play songs incorrectly.

## Actual Behavior
mpd fails to reopen the audio output to the song's format (missing line `output: opened "pulse audio" (pulse) audio_format=48000:16:2`), instead keeping the audio format of the previous or next song (not sure which). If the songs' bit depths do not match, this results in wholly garbled and loud/clipping audio output, and (if 16-bit audio is being played as 24-bit) audio plays 50% faster than correct.

Seeking in a client app loads the correct song length and fixes the audio volume.

Since I've only seen this bug happen on short songs (three times so far, though only one with verbose logs), I suspect (but am not sure) that this bug occurs because on short songs, `decoder_thread: probing plugin mad` immediately tries to preload the next queued song, and loads the *next* song's length and sample format *before* the player thread picks up the current song's format and sends it to the output thread. I have not been able to replicate this bug on command; I found that `AudioOutputControl::Open()` gets called nonstop during regular playback *within* a song, and haven't yet traced where the audio format comes from.

I did notice that in the most recent occurrence (where I took a log), the main IO thread was stuck processing a `command "sticker "set" "song" "Zelda, The Wind Waker Official Soundtrack/232 - Sage Fodo.mp3" "elapsed" "0""` for the entirety of probing the next song's audio format. I do not know if that's the cause of the bug.

## Version

`Music Player Daemon 0.23.14 (0.23.14-1+)` (Arch Linux)

## Configuration

```
# Recommended location for database
db_file            "~/.config/mpd/database"

# If running mpd using systemd, delete this line to log directly to systemd.
#log_file           "syslog"

# The music directory is by default the XDG directory, uncomment to amend and choose a different directory
music_directory    "~/mpd"

# Uncomment to refresh the database whenever files in the music_directory are changed
auto_update "yes"

# Uncomment to enable the functionalities
playlist_directory "~/.config/mpd/playlists"
pid_file           "~/.config/mpd/pid"
state_file         "~/.local/state/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

audio_output {
        type            "pulse"
        name            "pulse audio"
}

connection_timeout     "120"

replaygain                     "auto"

log_level "verbose"
```

## Log

Note that `zelda-oot/Nocturne of Shadow.flac` is a short song (22 seconds) in 48000:16:2 format, queued at the beginning of the logs and played in the middle (after `player: played` [previous song]). The song plays garbled, because mpd erroneously keeps PulseAudio output set to the 44100:24:2 format of the previous and subsequent song.

<details>

```
Nov 15 13:55:33 servlet mpd[3458424]: playlist: queue song 275:"zelda-oot/Nocturne of Shadow.flac"
Nov 15 13:55:34 servlet mpd[3458424]: output: opened "pulse audio" (pulse) audio_format=44100:24:2
Nov 15 13:55:34 servlet mpd[3458424]: replay_gain: replay gain mode has changed off->track
Nov 15 13:55:34 servlet mpd[3458424]: replay_gain: scale=1
Nov 15 13:55:34 servlet mpd[3458424]: replay_gain: scale=1.0161744
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "status"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "status"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "currentsong"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "sticker "set" "song" "ssbm/saria.flac" "elapsed" "0""
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "idle database stored_playlist playlist player mixer output options update partition"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 1
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] process command "currentsong"
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "getvol"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command list
Nov 15 13:55:34 servlet mpd[3458424]: client: process command "status"
Nov 15 13:55:34 servlet mpd[3458424]: client: command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: process command "currentsong"
Nov 15 13:55:34 servlet mpd[3458424]: client: command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command list returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "idle database stored_playlist playlist player mixer output options update partition"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 1
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "getvol"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "albumart "Zelda, The Wind Waker Official Soundtrack/232 - Sage Fodo.mp3" "0""
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 3
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "readpicture "Zelda, The Wind Waker Official Soundtrack/232 - Sage Fodo.mp3" "0""
Nov 15 13:55:34 servlet mpd[3458424]: mad: detected LAME version 3.92 ("LAME3.92 ")
Nov 15 13:55:34 servlet mpd[3458424]: mad: LAME peak found: 0
Nov 15 13:55:34 servlet mpd[3458424]: mad: encoder delay is 576, encoder padding is 2184
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] process command "idle database stored_playlist playlist player mixer output options update partition"
Nov 15 13:55:34 servlet mpd[3458424]: client: [4] command returned 1
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] process command "idle"
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] command returned 1
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:55:34 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:55:35 servlet mpd[3458424]: client: [551] process command "idle"
Nov 15 13:55:35 servlet mpd[3458424]: client: [551] command returned 1
Nov 15 13:56:04 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:56:04 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:56:05 servlet mpd[3458424]: client: [551] process command "idle"
Nov 15 13:56:05 servlet mpd[3458424]: client: [551] command returned 1
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] process command "playlistid "4483""
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] process command "sticker "set" "song" "Zelda, The Wind Waker Official Soundtrack/232 - Sage Fodo.mp3" "playCount" "1""
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] process command "sticker "set" "song" "Zelda, The Wind Waker Official Soundtrack/232 - Sage Fodo.mp3" "lastPlayed" "1700085334""
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:15 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:56:15 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] process command "idle database stored_playlist playlist player mixer output options update partition"
Nov 15 13:56:15 servlet mpd[3458424]: client: [4] command returned 1
Nov 15 13:56:16 servlet mpd[3458424]: client: [551] process command "idle"
Nov 15 13:56:16 servlet mpd[3458424]: client: [551] command returned 1
Nov 15 13:56:16 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:56:16 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:56:16 servlet mpd[3458424]: client: [551] process command "idle"
Nov 15 13:56:16 servlet mpd[3458424]: client: [551] command returned 1
Nov 15 13:56:43 servlet mpd[3458424]: decoder_thread: probing plugin flac
Nov 15 13:56:43 servlet mpd[3458424]: decoder: audio_format=48000:16:2, seekable=true
Nov 15 13:56:46 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:56:46 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:56:46 servlet mpd[3458424]: client: [551] process command "idle"
Nov 15 13:56:46 servlet mpd[3458424]: client: [551] command returned 1
Nov 15 13:56:53 servlet mpd[3458424]: player: played "Zelda, The Wind Waker Official Soundtrack/232 - Sage Fodo.mp3"
Nov 15 13:56:53 servlet mpd[3458424]: playlist: queue song 275:"Zelda, The Wind Waker Official Soundtrack/245 - Molgera (2nd Time).mp3"
Nov 15 13:56:53 servlet mpd[3458424]: client: [4] process command "status"
Nov 15 13:56:53 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:53 servlet mpd[3458424]: client: [4] process command "status"
Nov 15 13:56:53 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:53 servlet mpd[3458424]: client: [4] process command "currentsong"
Nov 15 13:56:53 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:53 servlet mpd[3458424]: client: [4] process command "sticker "set" "song" "Zelda, The Wind Waker Official Soundtrack/232 - Sage Fodo.mp3" "elapsed" "0""
Nov 15 13:56:54 servlet mpd[3458424]: decoder_thread: probing plugin mad
Nov 15 13:56:54 servlet mpd[3458424]: mad: detected LAME version 3.92 ("LAME3.92 ")
Nov 15 13:56:54 servlet mpd[3458424]: mad: LAME peak found: 0
Nov 15 13:56:54 servlet mpd[3458424]: mad: encoder delay is 576, encoder padding is 1788
Nov 15 13:56:54 servlet mpd[3458424]: decoder: audio_format=44100:24:2, seekable=true
Nov 15 13:56:54 servlet mpd[3458424]: replay_gain: scale=0.73113906
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command "idle database stored_playlist playlist player mixer output options update partition"
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 1
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] process command "currentsong"
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command "status"
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command list
Nov 15 13:56:54 servlet mpd[3458424]: client: process command "status"
Nov 15 13:56:54 servlet mpd[3458424]: client: command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: process command "currentsong"
Nov 15 13:56:54 servlet mpd[3458424]: client: command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command list returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command "sticker "set" "song" "zelda-oot/Nocturne of Shadow.flac" "elapsed" "0""
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [553] opened from 192.168.0.128:47714
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command "idle database stored_playlist playlist player mixer output options update partition"
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 1
Nov 15 13:56:54 servlet mpd[3458424]: client: [553] process command "albumart "zelda-oot/Nocturne of Shadow.flac" 0"
Nov 15 13:56:54 servlet mpd[3458424]: client: [553] command returned 3
Nov 15 13:56:54 servlet mpd[3458424]: client: [553] process command "readpicture "zelda-oot/Nocturne of Shadow.flac" 0"
Nov 15 13:56:54 servlet mpd[3458424]: client: [553] command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command "albumart "zelda-oot/Nocturne of Shadow.flac" "0""
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 3
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command "readpicture "zelda-oot/Nocturne of Shadow.flac" "0""
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 0
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] process command "idle database stored_playlist playlist player mixer output options update partition"
Nov 15 13:56:54 servlet mpd[3458424]: client: [4] command returned 1
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] process command "idle"
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] command returned 1
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] process command "status"
Nov 15 13:56:54 servlet mpd[3458424]: client: [551] command returned 0
```
</details>

**Comment by nyanpasu64** [comment]
I've decided to look into the code's threading to find out what caused the bug. Luckily I was able to trace a likely cause, based on reading the code and adding logs, tracing possible execution orderings and code behaviors, and cross-referencing the logs I captured of normal and broken code execution.

## Analysis

As a convention, assume that song #0 (a short song) started decoding while song -1 was playing. The bug happens when song -1 finishes playing, song +1 is queued to play, and (because song #0 is finished decoding) song +1 begins decoding while song #0 starts playing.

I've done a detailed trace of the control flow which results in this bug:

<details>

It's odd that `DecoderCommand` contains `mutex` and `client_cond` references. As far as I can tell they are initialized to `PlayerControl::mutex` and `PlayerControl::cond`, by `PlayerControl::RunThread()`.

- [x] what happens when song -1 is finished decoding and song #0 starts decoding?
	- player thread: `[Run] if (dc.IsIdle() && queued && IsDecoderAtCurrentSong()) {`
		- `Player::StartDecoder()` -> `DecoderControl::Start()` emits `DecoderCommand::START`.
		- does not interrupt control flow.
	- decoder thread: `[RunThread] case DecoderCommand::START: decoder_run(*this);`
- [x] what happens when song -1 is finished playing? (assume song #0 is finished decoding.)
	- player thread `[Player::Run()]`:
		- `if (!pipe->IsEmpty()) (false)`
		- `else if (Player::IsDecoderAtNextSong()) SongBorder() {`
			- `Player::pipe = DecoderControl::pipe;`
			- `Player::ActivateDecoder() {`
				- `Player::queued = false;`
				- `Player::song = take(PlayerControl::next_song);`
				- `Player::decoder_starting = true;` (!1)
				- `PlayerControl::audio_format.Clear();`
				- unlock `PlayerControl::mutex {`
					- `PlayerControl::listener.OnPlayerSync();`
						- emit `SYNC_WITH_PLAYER`
		- `} continue`
	- ui thread:
		- if `SYNC_WITH_PLAYER` ...
			- `playlist::SyncWithPlayer()`
				- `playlist::UpdateQueuedSong()`
					- `playlist::QueueSongOrder()`
						- "queue song {}"
						- `PlayerControl::LockEnqueueSong()`
							- `std::unique_lock<Mutex> lock(PlayerControl::mutex);`
							- `PlayerControl::EnqueueSongLocked()`
								- emit `PlayerCommand::QUEUE`
	- player thread `[Player::Run()]`:
		- (loop) `Player::ProcessCommand(lock) {`
			- `match PlayerControl::command`
				- `PlayerCommand::QUEUE:`
					- `assert(pc.next_song != nullptr);`
					- `assert(!queued);`
					- `assert(!IsDecoderAtNextSong());`
					- `Player::queued = true;`
					- ...
					- `if (DecoderControl::IsIdle())` (true, we "assume song #0 is finished decoding")
						- `Player::StartDecoder(lock, std::make_shared<MusicPipe>(), false);`
							- ...
							- overwrite `DecoderControl::song` etc.
							- emit `DecoderCommand::START`
							- `while (DecoderCommand::command != DecoderCommand::NONE)`
								- `(DecoderCommand::client_cond = PlayerControl::cond).wait(lock);`
- [x] what happens when song +1 starts decoding?
	- decoder thread:
		- `DecoderControl::RunThread() {`
			- `case DecoderCommand::START: decoder_run(DecoderControl);`
				- `decoder_run_song() {`
					- `DecoderControl::state = DecoderState::START;`
					- ...
					- `DecoderUnlockedRunUri(bridge, uri, path_fs) { ...`
						- `DecoderBridge::Ready() {`
							- "audio_format={}, seekable={}"
							- `DecoderControl::SetReady(audio_format, _seekable=seekable, _duration=duration) {`
								- `assert(DecoderControl::state == DecoderState::START);`
								- `assert(DecoderControl::pipe != nullptr);`
								- `assert(DecoderControl::pipe->IsEmpty());`
								- `assert(audio_format.IsDefined());`
								- `assert(audio_format.IsValid());`
								- `DecoderControl::in_audio_format = audio_format;` (!2)
								- `DecoderControl::out_audio_format = audio_format.WithMask(configured_audio_format);`
								- ...
								- `DecoderControl::total_time = _duration;`
								- `DecoderControl::state = DecoderState::DECODE;`
- [x] when is song #0 pushed to speakers with song +1's settings?
	- player thread `[Player::Run()]` ctd:
		- `} Player::ProcessCommand(lock)`
		- `if (Player::decoder_starting) (true) {` (see !1)
			- `Player::CheckDecoderStartup(lock) {`
				- `assert(decoder_starting);` (tautological unless data races)
				- ... `if (!dc.IsStarting())`
				- `^ = if (DecoderControl::state != DecoderState::START) {`
					- `PlayerControl::total_time = ...(DecoderControl::total_time)` (corrupted by !2)
					- `PlayerControl::audio_format = DecoderControl::in_audio_format;`
					- `Player::play_audio_format = DecoderControl::out_audio_format;`
						- **the perfect crime.**
					- `Player::decoder_starting = false;`
				- `} else {`
					- // the decoder is not yet ready; wait some more
					- `dc.WaitForDecoder(lock);`
					- `return true;`
			- `if !^ { break; } // error`
			- `continue;`

</details>

----

In short, the bug occurs because:

- When song -1 finishes playing and the player thread emits `SYNC_WITH_PLAYER`, sometimes the UI thread emits `PlayerCommand::QUEUE` to the player thread before `Player::Run()` can call `Player::CheckDecoderStartup()`.
- When the player thread checks `Player::ProcessCommand()` and processes `PlayerCommand::QUEUE`, the handler assumes that `DecoderControl::IsIdle()` means we can safely emit `DecoderCommand::START` and ask `DecoderControl` to decode the song being queued (+1).

This is not safe if we are preparing to play a song (#0), `Player::decoder_starting` is set, and we're waiting for `Player::CheckDecoderStartup()` to execute and read `DecoderControl::out_audio_format` and friends.

## Reproduction

I attempted to reliably replicate this bug by adding a 10 millisecond wait to `Player::ActivateDecoder()` after `pc.listener.OnPlayerSync()` (before acquiring the mutex again). Instead, this triggered a *program crash(!)* at an assertion error:

```
mpd: ../../../../code/MPD/src/player/Thread.cxx:814: void PlayerControl::PlayChunk(DetachedSong&, MusicChunkPtr, const AudioFormat&): Assertion `chunk->CheckFormat(format)' failed.

>bt
#4  0x00007fd0f1e2fd26 in __assert_fail () from target:/usr/lib/libc.so.6
#5  0x00005556e0c83d0d in PlayerControl::PlayChunk (this=<optimized out>, song=..., chunk=..., format=...) at ../../../../code/MPD/src/player/Thread.cxx:811
#6  PlayerControl::PlayChunk (format=..., chunk=..., song=..., this=0x5556e0e446d8) at ../../../../code/MPD/src/player/Thread.cxx:811
#7  Player::PlayNextChunk (this=0x7fd0dbffe550) at ../../../../code/MPD/src/player/Thread.cxx:929
#8  Player::Run (this=0x7fd0dbffe550) at ../../../../code/MPD/src/player/Thread.cxx:1080
#9  do_play (buffer=..., dc=..., pc=...) at ../../../../code/MPD/src/player/Thread.cxx:1160
#10 PlayerControl::RunThread (this=0x5556e0e446d8) at ../../../../code/MPD/src/player/Thread.cxx:1186
#11 0x00005556e0c9fa68 in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>, this=<optimized out>) at ../../../../code/MPD/src/util/BindMethod.hxx:77
#12 Thread::Run (this=0x5556e0e44708) at ../../../../code/MPD/src/thread/Thread.cxx:63
#13 Thread::ThreadProc (ctx=0x5556e0e44708) at ../../../../code/MPD/src/thread/Thread.cxx:92
#14 0x00007fd0f1e859eb in ?? () from target:/usr/lib/libc.so.6
#15 0x00007fd0f1f09654 in clone () from target:/usr/lib/libc.so.6
```

At `player/Thread.cxx:814`, you will find an assertion:

```cpp
inline void
PlayerControl::PlayChunk(DetachedSong &song, MusicChunkPtr chunk,
			 const AudioFormat &format)
{
	assert(chunk->CheckFormat(format));
...

bool
MusicChunkInfo::CheckFormat(const AudioFormat other_format) const noexcept
{
	assert(other_format.IsValid());

	return length == 0 || audio_format == other_format;
}
```

I believe that in `MusicChunkInfo::CheckFormat()`, the test `audio_format == other_format` always returns `false`, because `chunk` (from song #0) is being played using `format` (from `DecoderControl` and song +1). This results in an assertion failure and program crash.

Why did I previously get garbled audio rather than a crash? I think this assertion did not fire in Arch Linux's release build of mpd, because it was compiled with `_NDEBUG` defined, which removes the ability to catch the error after it occurs (but too late to find out *why* it happened).

**Comment by nyanpasu64** [comment]
## Discussion

My understanding is that the bug will occur if all of the following occurs:

- (UI thread) `SYNC_WITH_PLAYER -> playlist::SyncWithPlayer()` must lock `PlayerControl::mutex`, before (player thread) `Player::ActivateDecoder() -> ScopeUnlock` is destroyed and locks it.
	- I know because making the player thread sleep before `ScopeUnlock` is destroyed, makes the crash happen reliably (over 50% of the time) on short songs.
- When (player thread) `PlayerCommand::QUEUE` is processed, `dc.IsIdle()` must be true (which is only the case if song #0 is short enough it can be fully decoded before song -1 finishes playing).
	- I know because even with the sleep added, the crash does not happen if song #0 is normal (multiple minutes long). A long song does not finish decoding before it starts playing, meaning that `dc.IsIdle()` is false when song +1 is queued. This prevents song +1 from being decoded and crashing.

I observed that if song #0 is short but shares an audio format with song +1, it is played back correctly (without a crash) due to using the correct audio format, but the UI incorrectly shows the song length of the subsequent song.

How could we fix this bug from happening?

- [ ] If we want `DecoderControl` to only process one song at a time, then while `Player::decoder_starting` is set, `Player::ProcessCommand()` could avoid calling `Player::StartDecoder() -> emit DecoderCommand::START`.
	- [ ] Alternatively it could avoid processing `PlayerCommand::QUEUE` at all. This code would be delayed to after `Player::CheckDecoderStartup()` successfully reads the parameters of the previously decoded song from `DecoderControl`, and clears `Player::decoder_starting`.
		- [ ] Since we only have one command slot, leaving `PlayerCommand::QUEUE` in place may increase the chances of another command sent to `Player` overwriting `PlayerCommand::QUEUE`. Is it worth rewriting inter-thread communication using dedicated message channels/queues?
	- [ ] Is it safe for `Player::ProcessCommand()` to handle `PlayerCommand::QUEUE` but *not* call `Player::StartDecoder() -> emit DecoderCommand::START`? Right now we skip calling `StartDecoder()` if `dc.IsIdle()` is false. Skipping `StartDecoder()` would be unsafe (and lead to song +1 never getting decoded) if `DecoderCommand` automatically checks for pending commands when a song ends, but not when idle.
	- [ ] Would it fix the bug without unwanted side effects, if `Player::ProcessCommand()` emitted `DecoderCommand::START` *without* giving up the `DecoderControl/PlayerControl` mutex?
- If we want `DecoderControl` to process a song while another song is being processed, you would need a way to match each start command from `Player` with a reply from `DecoderControl`. You could embed a writable object into the request (which the sender holds a `shared_ptr` to), use a more heavyweight message bus, etc.
	- I wouldn't pick this option, as I think this is a lot of refactoring for limited benefit.

----

I cannot guarantee my fixes prevent *all* concurrency bugs resulting in incorrect audio formats from occurring. I've found and demonstrated one likely path for the malfunction to happen, but I do not know if there are other codepaths which cause this error (incorrect audio format noise) or others (edge-case race conditions like this, or data races and other undefined behavior).

Half-baked rambling:
<details>

Condition variables allow unbounded mutation to data previously protected by a mutex lock. I don't know if the locking used in this program prevent all data races or not, whereas Rust mutexes wrap data and only allow accessing data (through a `MutexGuard`) while its corresponding mutex is locked on the current thread. (Unfortunately, poisoning makes the Rust `Condvar` API unpleasant to use, requiring you pass a `MutexGuard` by move rather than reference).
</details>

**Comment by nyanpasu64** [comment]
Pushed my code to https://github.com/nyanpasu64/MPD/tree/debug. This branch contains some debugging commits to reproduce the bug consistently, and a fix for the bug (which should prevent the crash path I discovered, and works fine in my testing).

Note that my branch is based off v0.23.14, though it seems that master is *substantially* different from your release tags? Are there some unreleased refactors that you're working on?

**Comment by MaxKellermann** [comment]
@nyanpasu64, sorry for this late reply. I have your bug report in a tab often but never had enough time to wrap my head around this, because my time has been very scarce recently. Thanks a LOT for your detailed analysis, that is very much appreciated, that was extremely helpful. Your fix however does not work well because it doesn't set the `queued` field; I found a different fix that is more robust.
